<?php
define('_tongdai',  'Call Center');
define('_loichao',  'Let us explore with you Phu Quoc Pearl Island!');
define('_trangchu',  'Home');
define('_hoten',  'Full name');
define('_dienthoai',  'Phone');
define('_diachi',  'Address');
define('_noidung',  'Content');
define('_maxacnhan',  'Verification code');
define('_guilienhe',  'Send contact');
define('_xemtatca',  'View all');
define('_camnangdulich',  'Travel Guide');
define('_diemdenyeuthich',  'Favorite Destination');
define('_dattour',  'Booking tour');
define('_tourhangngay',  'Daily tour');
define('_tournoibat',  'Featured tour with good price');
define('_sologantournoibat',  'Feel the Phu Quoc offers daily tours at super good prices');
define('_giatot',  'Good price');
define('_thoigian',  'Time');
define('_lichkhoihanh',  'Departure schedule');
define('_phuongtien',  'Vehicle');
define('_khampha',  'Discover now');
define('_ketnoi',  'Connect with us');
define('_lienhe',  'Contact');
define('_intour',  'Print tour info');
define('_chuongtrinh',  'Tour program');
define('_chinhsach',  'Tour policy');
define('_dieukhoan',  'Terms and Regulations');
define('_tourtuongtu',  'Similar tours');
define('_tintuongtu',  'Similar news');
define('_ngaydang',  'Date Submitted');
define('_luotxem',  'View');
define('_moinhat',  'Latest');
define('_xemnhieunhat',  'Most view');
define('_giathapcao',  'Price from high to low');
define('_giacaothap',  'Price from low to high');
define('_tenaz',  'Name in order from A to Z');
define('_tenza',  'Name in order from Z to A');
define('_timkiem',  'Search');
?>