<?php
define('_tongdai',  'Tổng đài tư vấn');
define('_loichao',  'Hãy để chúng tôi cùng bạn khám phá Đảo Ngọc Phú Quốc!');
define('_trangchu',  'Trang chủ');
define('_hoten',  'Họ và tên');
define('_dienthoai',  'Điện thoại');
define('_diachi',  'Địa chỉ');
define('_noidung',  'Nội dung');
define('_maxacnhan',  'Mã xác nhận');
define('_guilienhe',  'Gửi liên hệ');
define('_xemtatca',  'Xem tất cả');
define('_camnangdulich',  'Cẩm nang du lịch');
define('_diemdenyeuthich',  'Điểm đến yêu thích');
define('_dattour',  'Đặt tour');
define('_tourhangngay',  'Tour hằng ngày');
define('_tournoibat',  'Tour nổi bật giá tốt');
define('_sologantournoibat',  'Feel the Phú Quốc cung cấp bộ tour hàng ngày giá siêu tốt');
define('_giatot',  'Giá tốt');
define('_thoigian',  'Thời gian');
define('_lichkhoihanh',  'Lịch khởi hành');
define('_phuongtien',  'Phương tiện');
define('_khampha',  'Khám phá ngay');
define('_ketnoi',  'Kết nối với chúng tôi');
define('_lienhe',  'Liên hệ');
define('_intour',  'In tour');
define('_chuongtrinh',  'Chương trình tour');
define('_chinhsach',  'Chính sách tour');
define('_dieukhoan',  'Điều khoản và Quy định');
define('_tourtuongtu',  'Các tour tương tự');
define('_tintuongtu',  'Tin tương tự');
define('_ngaydang',  'Ngày đăng');
define('_luotxem',  'Lượt xem');
define('_moinhat',  'Mới nhất');
define('_xemnhieunhat',  'Xem nhiều nhất');
define('_giathapcao',  'Giá từ thấp đến cao');
define('_giacaothap',  'Giá từ cao đến thấp');
define('_tenaz',  'Tên theo thứ tự từ A -> Z');
define('_tenza',  'Tên theo thứ tự từ Z -> A');
define('_timkiem',  'Tìm kiếm');
?>